import Navbar from './components/Navbar'
import './globals.css'
import { Rubik } from 'next/font/google'
//components

//configuration object for font
const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={rubik.className}>
				<header>
					<Navbar />
				</header>
				{children}
			</body>
		</html>
	)
}
